/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JPanel;

/**
 *
 * @author riaka
 */
public class AdminInfoJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    
    public AdminInfoJPanel(JPanel workA) {
        initComponents();
        this.workArea=workA;
    }

    /**
     * Creates new form AdminInfoJPanel
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminInfo = new javax.swing.JLabel();
        btnStudentList = new javax.swing.JButton();
        btnRevenue = new javax.swing.JButton();
        btnAddCourses = new javax.swing.JButton();
        btnAddFaculty = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAdminInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAdminInfo.setForeground(new java.awt.Color(0, 153, 255));
        lblAdminInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminInfo.setText("Admin");

        btnStudentList.setText("Student List");

        btnRevenue.setText("Check Revenue");

        btnAddCourses.setText("Add Courses");

        btnAddFaculty.setText("Add Faculty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentList, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAdminInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAdminInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStudentList)
                .addGap(18, 18, 18)
                .addComponent(btnRevenue)
                .addGap(18, 18, 18)
                .addComponent(btnAddCourses)
                .addGap(18, 18, 18)
                .addComponent(btnAddFaculty)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourses;
    private javax.swing.JButton btnAddFaculty;
    private javax.swing.JButton btnRevenue;
    private javax.swing.JButton btnStudentList;
    private javax.swing.JLabel lblAdminInfo;
    // End of variables declaration//GEN-END:variables
}
