/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author riaka
 */
public class FacultyInfoJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    
    public FacultyInfoJPanel(JPanel workA) {
        initComponents();
        this.workArea=workA;
    }

    /**
     * Creates new form FacultyInfoJPanel
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacultyInfo = new javax.swing.JLabel();
        btnFacultyDashboard = new javax.swing.JButton();
        btnCheckRating = new javax.swing.JButton();
        lblFacultyImage = new javax.swing.JLabel();

        lblFacultyInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFacultyInfo.setForeground(new java.awt.Color(0, 153, 255));
        lblFacultyInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultyInfo.setText("Faculty");

        btnFacultyDashboard.setText("Faculty Dashboard");
        btnFacultyDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyDashboardActionPerformed(evt);
            }
        });

        btnCheckRating.setText("Check Rating");

        lblFacultyImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\riaka\\Downloads\\icons8-teacher-48 (1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblFacultyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFacultyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCheckRating, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacultyDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblFacultyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFacultyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnFacultyDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnCheckRating)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacultyDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyDashboardActionPerformed
        // TODO add your handling code here:
        FacultyDashboard facultydash = new FacultyDashboard(workArea);
            workArea.add("FacultyDashboard", facultydash);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
    }//GEN-LAST:event_btnFacultyDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckRating;
    private javax.swing.JButton btnFacultyDashboard;
    private javax.swing.JLabel lblFacultyImage;
    private javax.swing.JLabel lblFacultyInfo;
    // End of variables declaration//GEN-END:variables
}
