/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.io.File;
import model.AdminLogin;
import model.AlumniLogin;
import model.Dashboard;
import model.FacultyLogin;
import model.StudentLogin;

/**
 *
 * @author riaka
 */
public class MainJFrame extends javax.swing.JFrame {
    StudentLogin studentlogin;
    FacultyLogin facultylogin;
    AlumniLogin alumnilogin;
    AdminLogin adminlogin;
    Dashboard dashboard;
    

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        studentlogin = new StudentLogin();
        facultylogin = new FacultyLogin();
        alumnilogin = new AlumniLogin();
        adminlogin = new AdminLogin();
        dashboard = new Dashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnStudentLogin = new javax.swing.JButton();
        btnFacultyLogin = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnAlumniLogin = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(100);
        splitPane.setLastDividerLocation(95);
        splitPane.setPreferredSize(new java.awt.Dimension(490, 320));

        controlPanel.setAlignmentX(0.0F);
        controlPanel.setAlignmentY(0.0F);
        controlPanel.setPreferredSize(new java.awt.Dimension(190, 298));

        btnStudentLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnStudentLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\riaka\\Downloads\\icons8-student-male-48.png")); // NOI18N
        btnStudentLogin.setText("Student Login");
        btnStudentLogin.setPreferredSize(new java.awt.Dimension(155, 59));
        btnStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLoginActionPerformed(evt);
            }
        });

        btnFacultyLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnFacultyLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\riaka\\Downloads\\icons8-teacher-48.png")); // NOI18N
        btnFacultyLogin.setText("Faculty Login");
        btnFacultyLogin.setPreferredSize(new java.awt.Dimension(155, 59));
        btnFacultyLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyLoginActionPerformed(evt);
            }
        });

        btnAdminLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAdminLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\riaka\\Downloads\\icons8-admin-settings-male-64.png")); // NOI18N
        btnAdminLogin.setText("Admin Login");
        btnAdminLogin.setPreferredSize(new java.awt.Dimension(155, 59));
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\riaka\\Downloads\\icons8-dashboard-layout-48.png")); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setPreferredSize(new java.awt.Dimension(155, 59));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnAlumniLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAlumniLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\riaka\\Downloads\\icons8-graduation-scroll-50.png")); // NOI18N
        btnAlumniLogin.setText("Alumni Login");
        btnAlumniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumniLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFacultyLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnStudentLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAdminLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlumniLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFacultyLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlumniLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLoginActionPerformed
        // TODO add your handling code here:
         //StudentLoginJPanel studentlog = new StudentLoginJPanel(workArea,studentlogin);
        //splitPane.setBottomComponent(studentlog);
        StudentLoginJPanel studentlogin= new StudentLoginJPanel(workArea);
            workArea.add("StudentLoginJPanel", studentlogin);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
    }//GEN-LAST:event_btnStudentLoginActionPerformed

    private void btnFacultyLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyLoginActionPerformed
        // TODO add your handling code here:
       // FacultyLoginJPanel facultylog = new FacultyLoginJPanel(facultylogin);
       // splitPane.setBottomComponent(facultylog);
       FacultyLoginJPanel facultylog= new FacultyLoginJPanel(workArea);
            workArea.add("FacultyLoginJPanel", facultylog);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
    }//GEN-LAST:event_btnFacultyLoginActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        //AdminLoginJPanel adminlog = new AdminLoginJPanel(adminlogin);
        //splitPane.setBottomComponent(adminlog);
        AdminLoginJPanel adminlog= new AdminLoginJPanel(workArea);
            workArea.add("AdminLoginJPanel", adminlog);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnAlumniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumniLoginActionPerformed
        // TODO add your handling code here:
      //  AlumniLoginJPanel alumnilog = new AlumniLoginJPanel(alumnilogin);
      //  splitPane.setBottomComponent(alumnilog);
        AlumniLoginJPanel alumnilog= new AlumniLoginJPanel(workArea);
            workArea.add("AlumniLoginJPanel", alumnilog);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
    }//GEN-LAST:event_btnAlumniLoginActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
      // DashboardJPanel dash = new DashboardJPanel(dashboard);
      //  splitPane.setBottomComponent(dash);
        DashboardJPanel dash= new DashboardJPanel(workArea);
            workArea.add("DashboardJPanel", dash);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnAlumniLogin;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnFacultyLogin;
    private javax.swing.JButton btnStudentLogin;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
